import './globals.css'

export const metadata = {
  title: 'Jimmy Alves Da Silva - Web Developer - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang='en'>    
      <body className="bg-[#F5F5F5] font-noto-sans-tamil">{children}</body>
    </html>
  )
}
